version: '3.1'

services:

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: always
    ports:
      - 80:80
    volumes:
      - ./wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wpdb
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: root
    depends_on:
      - db
  
  db:
    image: mysql:latest
    container_name: mysqldbwp 
    restart: always
    volumes:
      - ./dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wpdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: rootpswd

  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - db
    ports:
      - 8082:80

volumes:
  dbdata:
    driver: local